### Tensors Basics

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [4]:
import torch
import numpy as np

In [5]:
torch.__version__

'1.9.0+cpu'

#### Numpy Array

In [7]:
lst = [3,4,5,6]
arr = np.array(lst)
arr

array([3, 4, 5, 6])

#### Convert Numpy to Pytorch Tensors

In [9]:
tensors = torch.from_numpy(arr)
tensors

tensor([3, 4, 5, 6], dtype=torch.int32)

In [10]:
### Indexing similar to numpy
tensors[2]

tensor(5, dtype=torch.int32)

In [11]:
tensors[1:4]

tensor([4, 5, 6], dtype=torch.int32)

#### Disadvantage of from_numpy. The array and tensor uses the same memory location

In [12]:

tensors[3]=100

In [13]:
tensors

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [14]:
arr

array([  3,   4,   5, 100])

Here we observe that changes made to tensor also reflects in numpy array because both use the same memory locations.
to prevent this we use torch.tensors instead of torch.from_numpy

#### Prevent this by using torch.tensor

In [17]:
### Prevent this by using torch.tensor
tensor_arr = torch.tensor(arr)
tensor_arr

tensor([  3,   4,   5, 100], dtype=torch.int32)

In [18]:
tensor_arr[3] = 120
print(tensor_arr)
print(arr)

tensor([  3,   4,   5, 120], dtype=torch.int32)
[  3   4   5 100]


#### Zeros and Ones

In [19]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [20]:
torch.ones(2,3,dtype=torch.float64)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

#### Logic driven tensors

In [21]:
a = torch.tensor(np.arange(0,15).reshape(5,3))
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [22]:
a[:,0:2]

tensor([[ 0,  1],
        [ 3,  4],
        [ 6,  7],
        [ 9, 10],
        [12, 13]], dtype=torch.int32)

#### Arithmetic Operation

In [23]:
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
print(a + b)

tensor([ 7.,  9., 11.])


In [24]:
torch.add(a,b)

tensor([ 7.,  9., 11.])

In [26]:
c = torch.zeros(3)

In [27]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [28]:
c

tensor([ 7.,  9., 11.])

In [29]:
##### Some more operations
a = torch.tensor([3,4,5], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)
### tensor[7,9,15]
torch.add(a,b).sum()

tensor(27.)

#### Dot Products and Mult Operations

In [30]:
x = torch.tensor([3,4,5], dtype=torch.float)
y = torch.tensor([4,5,6], dtype=torch.float)

In [31]:
x.mul(y)

tensor([12., 20., 30.])

In [32]:
x.dot(y)

tensor(62.)

#### Matrix Multiplication

In [33]:
x = torch.tensor([[1,4,2],[1,5,5]], dtype=torch.float)
y = torch.tensor([[5,7],[8,6],[9,11]], dtype=torch.float)

In [34]:
torch.matmul(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [35]:
torch.mm(x,y)

tensor([[55., 53.],
        [90., 92.]])

In [36]:
x@y

tensor([[55., 53.],
        [90., 92.]])